### ISSUE TITLE
[Request] Client-sided preset saving

### ISSUE THREAD

**Issue by Ringlings** [sisby-folk/switchy#1]
A way to:

- Fetch configs from the server and save them to the client
- Send configs from the client to autofill presets
- *Optionally* a way to keep configuration client side

This would make transferring presets between servers easier, as it doesn't require entering the presets again and again on every server you want to use them on.

Another way we could see this working (which would require a bit of rewriting the mod, and may be out of scope) is to have configuration completely on the client-side, and to send the relevant information for switches to the server.

**Comment by sisby-folk** [comment]
This one's definitely going to require some thinking - by sneakily *not*
reimplementing anyone else's commands and keeping presets with playerData,
we're actually deferring to the permissions of those commands (if you can't
use /nick, you can't set a preset with /nick)

We'll probably just lock this issue behind completing the config system, to
allow certain values being changed to be turned off entirely.

And yeah, definitely custom packets for `/switchy import` and `/switchy
export`

**Comment by sisby-folk** [comment]
Exporting to clients is officially A Thing as of 1.6.0

Importing is still to come.

**Comment by sisby-folk** [comment]
Oh, yeah, this is done @Ringlings as of 1.7
