### ISSUE TITLE
[Bug] Incompatibility with FTB Quests (1.19 Only)

### ISSUE THREAD

**Issue by Infinidoge** [sisby-folk/switchy#15]
When FTB Quests is used with Switchy versions >= 1.4.2+1.19, the entire background (and many elements) of the quests screen is completely transparent. Notably, this only occurs on the 1.19 versions. None of the 1.18 versions in the same range exhibit this problem

#### Other Mods Installed
- Architectury 6.3.49
- FTB Library 1902.3.9-build.144
- FTB Quests 1902.4.2-build.116
- FTB Teams 1902.2.9-build.61
- Item Filters 1902.2.9-build.46
- Quilted Fabric API 4.0.0-beta.19+0.64.0-1.19.2

#### Screenshots
Screenshots taken with a black concrete background

##### Switchy >= 1.4.2+1.19 (Tested on 1.4.2, 1.4.3, 1.5.0, 1.5.1 [built from source])
![2022-11-05_16 34 59](https://user-images.githubusercontent.com/22727114/200140256-0b3b6739-3493-46c6-bbbf-ada07207869d.png)

##### Switchy <= 1.4.1+1.19 (Tested on 1.4.1)
![2022-11-05_16 37 04](https://user-images.githubusercontent.com/22727114/200140317-8263c638-d412-42f5-8e13-f9f9e2ecf9bc.png)

**Comment by sisby-folk** [comment]
Sorted in 1.5.2, carrying over to 1.6.0 - Basically, FTB quests is doing total nonsense to load its textures, which the `include`'d kdlydata breaks. Just gonna have to not use kdly for now, considering the priority of not messing with TQuilt.
