### ISSUE TITLE
Get presets & switch preset API methods

### ISSUE THREAD

**Issue by Ampflower** [sisby-folk/switchy#16]
*Discussed in DMs*

Expose API methods that allow for getting currently registered presets, along with switching to another preset?

**Comment by sisby-folk** [comment]
Added in 1.17.2! Have fun ^^

(nb: with the current `SwitchyPresets.importFromOther` method, it would be possible to create a pk integration mod that can import a system's worth of names, colors and pronouns just by constructing NBT in the way switchy modules expect)
