### ISSUE TITLE
Pehkui Size Does Not Save

### ISSUE THREAD

**Issue by sylv256** [sisby-folk/switchy#17]
The Pehkui size does not save when leaving and rejoining the game, instead reverting back to 100%.
This could possibly be a Pehkui bug, but I suspect it's switchy.

**Comment by sisby-folk** [comment]
mm, we should probably set `persistent true` huh. The difficulty is that
that does go against our command permission pass through methodology.

**Comment by sisby-folk** [comment]
Persistence shouldn't apply to leaving and re-logging, and switchy doesn't perform any operations on the player during join - so I'm gonna close this as invalid unless there's anything else found.
