### ISSUE TITLE
[Request] Fabric port?

### ISSUE THREAD

**Issue by ghost** [sisby-folk/switchy#18]
Hello! This is an amazing mod that opens us so many possibilities, but a lot of great mods are on fabric. We wish this mod supported fabric because there are no alternatives for our desired modloader. If it won't be too hard for you folks to port the mod, it would be awesome.

Have a great day!

**Comment by sisby-folk** [comment]
Hey there! is there a specific fabric mod you need to use that doesn't load
on Quilt? Most fabric mod lists will load on quilt just fine.

**Comment by ghost** [comment]
I'm sorry for my wording. I meant can you port Switchy to Fabric? We already have an established modpack on Fabric, and adding Switchy would help a lot for us personally. But we can't add it because Switchy is made for Quilt. Thank you in advance.

**Comment by sisby-folk** [comment]
To explain more clearly, if you have a modpack made in fabric, you can
simply change the loader to quilt and add Switchy, unless there is
specifically a fabric mod that breaks on quilt in the mod list.

If there is such a mod (that we feel would particularly benefit Switchy to
be in the same environment as), feel free to let us know.
