### ISSUE TITLE
Silent failure with `CardinalSerializerCompat.tryRegister` may be undesirable

### ISSUE THREAD

**Issue by SilverAndro** [sisby-folk/switchy#19]
Currently, `CardinalSerializerCompat.tryRegister` will silently eat an error if the requested key ID cannot be found, but this may cause issues depending on mod load order

As mods may attempt to call this method before CCA is done initializing, there may not be a component too look up yet, causing it to have no effect. Either this method should place the IDs in a queue until CCA is done, or it should warn that it couldnt find some ID rather than silently having no effect.

(I think this might also affect the modfest compat mods? You may have just gotten lucky due to random chance load order)

**Comment by sisby-folk** [comment]
We're up to hearing solutions for this - we made explicit compat references
to get the IDs for the modfest compats, because lib39 postinit was only
available on 1.19.

**Comment by SilverAndro** [comment]
I think the easiest would be to create a queue, and then use lib39 postinit for >1.19, and use mixin to hook after CCA's entrypoints for <1.19? You could have those set a flag to then automatically register modules instead of enqueuing them.

**Comment by sisby-folk** [comment]
okay so lib39 postinit for 1.18 is a thing now, so that's probably a solution we'll look into - we'll want the components themselves to be defineable using a config file, so we'll work on that.

**Comment by SilverAndro** [comment]
Sounds like a good solution

**Comment by sisby-folk** [comment]
Cool! With the new method in 1.8, the failure is warned and logged if it happens - plus it's more lenient now.
