### ISSUE TITLE
SwitchyChat / SwitchyProxy

### ISSUE THREAD

**Issue by sisby-folk** [sisby-folk/switchy#22]
for @0xf24

Using an existing system for detecting and using "Proxy tags", a `pk;ap front`-style chat can be achieved.

This requires
 - [x] Commands to set the proxy tag
 - [ ] A module, to store the proxy tags associated with each preset (`G: text` and so on)
 - [x] A way to retreive all of the proxy tag modules for a player at once for processing (new API endpoint - `SwitchyPlayer player, Identifier moduleId -> Map<Identifier, PresetModule>`)
 - [x] A system for detecting the proxy tag in a message and matching it against a list (from the map)
 - [x] A system for changing the display name of the sender for that one specific chat message, in a way that works in multiplayer (existing nickname mod issues?)

**Comment by sisby-folk** [comment]
Flow:

- Current preset: gel. Drogtor/Styled Nickname: "Gel"
- `/proxy add G: text` (or whatever) 
- `[SwitchyProxy] Added proxy for gel`
- <proxy is saved to the switchyproxy:proxies module>
- `/switch otherPreset`
- `[Switchy] switched from gel to otherPreset`
- `G: hi`
- [Gets all proxy modules for player] 
- [Matches against and finds proxy under key `gel`] 
- Get drogtor/styled nickname module for `gel`
- Use this nickname for the chat message
- `<Gel> hi`
- `hii`
- `<OtherName> hii`

**Comment by Oliver-makes-code** [comment]
It might make more sense to have a list of proxies that point to members, rather than members containing a list of proxies
This is the way that ProxyFox does it:
```kt
class MemberProxyTagRecord {
    var memberId: String = ""
    var prefix: String? = null
    var suffix: String? = null
}
```

**Comment by sisby-folk** [comment]
This is an option - though, keeping data in a module (which is inside a preset) means it will be deleted when a preset is deleted. Unsure how you could set that up with the above idea.

**Comment by sisby-folk** [comment]
Closed by [switchy-proxy](https://github.com/sisby-folk/switchy-proxy/releases/tag/v1.0.0)
