### ISSUE TITLE
SwitchyFiguraAPI listening functions are permanent

### ISSUE THREAD

**Issue by emifloofy** [sisby-folk/switchy#51]
When you load an avatar that uses the SwitchyFiguraAPI, and then reload it or load a different one, the listening functions from the first loaded avatar don't get removed.

This leads to the functions being ran multiple times after a switch, or the functions get ran while the avatar that uses the API isn't loaded anymore.

**Comment by Octelly** [comment]
Yeah, the previous LUA environment doesn't seem to get "discarded" on Switchy's side when an avatar reload occurs.

**Comment by emifloofy** [comment]
speaking of the SwitchyFiguraAPI, there's a small mistake in the documentation, where on [this line](https://github.com/sisby-folk/switchy/blob/aa58e78851ba2dcc67384254ea1bb7a79fc9efea/README.md?plain=1#L199), the oldPreset and newPreset are swapped.

**Comment by sisby-folk** [comment]
So this is theoretically fixed in 2.6.4 so please give it a try! I have no way of testing myself.
