### ISSUE TITLE
Crashes with Origins (Forge) when using Connector and FFAPI

### ISSUE THREAD

**Issue by nebulazorua** [sisby-folk/switchy#58]
When using Switchy in a Forge environment by using Connector and FFAPI, it crashes when trying to use Origins (Forge) alongside it.
I can't use the Fabric Origins running through Connector and FFAPI because then Tinkerer's Statures wouldnt recognise Origins as running.
When the mod runs without Origins and Tinkerer's Statures, everything works fine.
Log is at https://mclo.gs/RZPkygx

**Comment by nebulazorua** [comment]
![image](https://github.com/sisby-folk/switchy/assets/12458328/072c2bb9-3dc1-4813-8345-f197d075744b)
![image](https://github.com/sisby-folk/switchy/assets/12458328/9115d89b-7a82-4fdd-ace3-eb2ce4406bf7)

Oh yeah and here's the logs from Prism Launcher showing Origins not being detected through Connector and FFAPI, despite being in the mod list

**Comment by nebulazorua** [comment]
I had the wrong Forge version (47.2.0 instead of 47.1.3) but the same crash still persists even after downgrading

**Comment by sisby-folk** [comment]
Origins forge is basically a different mod, and their APIs are just not compatible in many places. Origins/Apoli is also a very extensive set of changes to the game, so it's extremely unlikely they'll ever run on connector unmodified for this reason.

In any case, we turned off the Apoli module and applied a reflection BS to make basic origin switching work on forge. pray it does not break lol, it's paper-thin. https://modrinth.com/mod/switchy/version/2.8.4+1.20

**Comment by nebulazorua** [comment]
Awesome
hopefully some day stuff can be more seamless between forge/fabric stuff

**Comment by sisby-folk** [comment]
neoforged is looking hopeful! a lot of sway away from the issues I specifically ran into (forge registries, lazy optionals, etc)

If cardinal ever ends up crossplat as a result, we'll be in interesting times.
