### ISSUE TITLE
[Bug] /Switch kills and overwrites profile

### ISSUE THREAD

**Issue by V-lpen** [sisby-folk/switchy#6]
I don't know how to diagnose, repeat, or fix this problem. This happened to two players on my server using Switchy + switchy inventories

quilt loader 0.17.5-beta.2 1.19.2 

Switchy-1.3.2+1.19
switchy-inventories-1.2.0+1.19.2
qfapi-4.0.0-beta.11_qsl-3.0.0-beta.15_fapi-0.60.0_mc-1.19.2

Players are on Fabric instead of Quilt, with switchy only being server-side.

Problem as occured:
Player switches with /switchy set (Name) , with module inventories and enderchest and trinkets enabled
Player is suddenly taken to death screen with no death message in chat, and cant respawn
Player relogs and logs back in to the previously enabled profile, with their last used profile overriding the one switched to, effectively erasing anything in the profile.  Any item or skin you had before switching gets put into whatever you tried to switch into. 

I hope this can be diagnosed or fixed easily because my friends have lost items that are put in other inventories. :(

**Comment by sisby-folk** [comment]
A few people have observed this now, but the lack of consistent replication makes it very hard to debug.

Additional environment info:

- Occurs on Quilt, even when Switchy is on the client side
- Occurs with both inventories and ender chests *off*

We're looking for two pieces of information here - one is the minimum modules + mods required to trigger this glitch - two is *any* hint as to the conditions under which it occurs. 

For 2, I haven't personally had access to server logs when this has happened to me - if you do and can see anything related, send it through.

**Comment by sisby-folk** [comment]
Our current guess is still that this occurs with the Trinkets module specifically.

We're posting a new version today that should (ideally) slightly improve error handling and logging for switch commands, assuming there are actually errors to handle.

**Comment by sisby-folk** [comment]
Extra info on this:

- It was isolated to the Fabric Tailor Module
- It occured due to fabric tailor making the player change-dimensions-style Respawn, invalidating the player object
- The actual issue occurred (as we understand) due to the copying in `ServerPlayerEntity` passing a `SwitchyPresets` object with a stale player reference held inside it.
- The need for a player reference inside the `SwitchyPresets` object was axed entirely.
