### ISSUE TITLE
2.90 not working on forge

### ISSUE THREAD

**Issue by magnacrabb** [sisby-folk/switchy#69]
trying to use 2.90 on forge with connector + ffapi ends in a crash, logs say its because switchy is asking for fabric api 0.15.1.

this probably because ffapi has not updated to support 0.15.1 yet, so idk what can be done on your end, but if nothing can be done the 2.90 version can be untagged as being forge compatible.

**Comment by sisby-folk** [comment]
Fixed in 2.9.1+1.20 (dropped FL version to 0.15.0)
