### ISSUE TITLE
Can't open UI

### ISSUE THREAD

**Issue by Oostveliske** [sisby-folk/switchy#72]
I can't open the UI when pressing the Semicolon Key

Fedora 39 Linux
Quilt
UK Keyboard Layout, have also tried on US and German

Installed Mods:
Pehkui
Quilt Kotlin Libraries
Quilted Fabric API
Styled Chat
Styled Nicknames
Styled Playerlist
Switchy
Switchy Inventory
Switchy Proxy
Switchy Status
Switchy Teleport
Switchy Kit

**Comment by sisby-folk** [comment]
missing https://modrinth.com/mod/owo-lib ? it's optional but enables the UI submod when installed.

**Comment by Oostveliske** [comment]
Yeah I was missing that. Thank you.
Maybe you could make it more obvious that owo-lib is needed for the UI.
In Launcher like Prism Launcher you don't see optional dependencies like when clicking on a Mod in Modrinth.
And on the main page on Modrinth the need for owo-lib is not mentioned next to the information that ; is the key to open the UI. That information is deeper in the Config and Developer Sections.
I would recommend putting the need for owo-lib for the UI right next to the explanation that ; is the key to open the UI.

Otherwise thank you and have a nice day.
