### ISSUE TITLE
Pehkui scales don't save

### ISSUE THREAD

**Issue by Snarke1** [sisby-folk/switchy#73]
I'm not using origins or statures but I am using Pehkui and Fabric Tailor. Whenever I make presets, It saves skins from Fabric Tailor just fine but scale changes from Pehkui don't seem to save to presets at all and are just universal.

**Comment by sisby-folk** [comment]
which pehkui scale types to save in Switchy are configured in a toml file on the server - by default it's only a few, so adjust it to match what you want.

**Comment by Snarke1** [comment]
What if I'm playing single player?

**Comment by sisby-folk** [comment]
then your singleplayer instance is the server - open config/switchy/ and edit the scale types config toml

**Comment by Snarke1** [comment]
Ah I found it. thank you!
