### ISSUE TITLE
Can duplicate items if you switch at same time as player killed.

### ISSUE THREAD

**Issue by LiEnby** [sisby-folk/switchy#77]
I'm pretty sure the timing on this is extremely precise but if you switch to another alter and have your player die at the same time, the items will both be in the previous alters inventory, and dropped on the ground, effectively duplicating them

this happened on our server with very low TPS, i could not get it to happen again after that and i tried a few times-

**Comment by sisby-folk** [comment]
we'll cover this under #62 - there's lots of issues with switches not being properly transactional
