### ISSUE TITLE
Fixing an issue, sorry if its basic

### ISSUE THREAD

**Issue by Fintris** [sisby-folk/switchy#9]
So i'm getting this issue: ModSolvingException: Unhandled error involving mod 'Switchy' (switchy) v1.3.3+1.19:
Dependency for mod 'switchy' on quilted_fabric_api versions [>=4.0.0-] (0 valid options, 0 invalid options)

I'm on the latest version of quilt and this mod, and on 1.19.2

**Comment by sisby-folk** [comment]
Switchy requires [QSL](https://modrinth.com/mod/qsl) - this isn't always listed on the modrinth files. as many quilt mods require QSL.

Hope that helps!

**Comment by Fintris** [comment]
Thanks, Im new to quilt
